## (0) Setup
Go through the setup instruction on our [Github Wiki](https://github.com/pro3d-space/PRo3D/wiki/Interactive-Co%E2%80%90Registration-Workflow). Jupyter setup concludes with executing the import cell 👇.

In [26]:
# imports
from typing import Any
import requests
import json
import open3d as o3d
import numpy as np
import subprocess

from pro3d_api import Pro3DClient
import data_io as io
import o3d_uitls as o3du

If not already running, start your PRo3D Instance with the following command line parameters

```
PRo3D.Viewer.exe --remoteApi --port 4321 
```

In [27]:
# create api client Pro3D instance
client = Pro3DClient(port=4321)

The [Github Wiki](https://github.com/pro3d-space/PRo3D/wiki/Interactive-Co%E2%80%90Registration-Workflow) also provides a walkthrough and additional infos on what this notebook does. Basically, all computational cells in this notebook must be executed in succession, while 👈 indicates, that some interaction is necessary in PRo3D.

## (1) Coarse Registration

* **Reference Surface (REF)**: This is the reference surface, what we consider as truth we want to align the movable surface to. The static part.
* **Movable Surface (MOV)**: The movable surface is the surface we want to transform during the registration process to align with the reference surface. The movable part.

### (1.1) Create Feature Points
In order to roughly align MOV to REF, we need to pick the same feature points on either surface. 

👈 Draw a polyline with **linear projection** on MOV and another one on REF. Both polylines, **must** have the **same number of points**, lie on the **same visual features**, and the points have to be **in the same order**. Minimum number is three, but we recommend to use 5 or 6 points.

👈 Select annotation drawn on MOV surface

In [29]:
# Retrieve selected annotation points as MOV feature points
mov_points = client.get_selected_annotation_points()

👈  Select annotation drawn on TGT surface

In [30]:
# Retrieve selected annotation points as MOV feature points
ref_points = client.get_selected_annotation_points()

### (1.2) Rigid Body Transformation

In [33]:
# Compute the rigid transformation matrix using Open3D
alignment_trafo = o3du.compute_rigid_transformation_from_correspondences(ref_points, mov_points)
print(alignment_trafo)

[[ 9.99278651e-01 -5.12201329e-04  3.79725700e-02 -3.86306918e+04]
 [ 8.57235258e-04  9.99958493e-01 -9.07067451e-03  9.26347161e+03]
 [-3.79663479e-02  9.09668281e-03  9.99237613e-01 -1.18965122e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


👈 Select MOV surface to be transformed

In [36]:
# Apply transformation to selected surface
client.apply_transformation_to_selected_surface(alignment_trafo, verbose=True)

✅ Transformation applied to surface selected
📦 Response: Received payload [[0.9992786506159889, -0.0005122013288448336, 0.03797257000635512, -38630.69177934702], [0.0008572352579089507, 0.9999584931444213, -0.009070674509198184, 9263.471606392879], [-0.03796634787283878, 0.009096682809571488, 0.9992376127783926, -1189.6512213787064], [0, 0, 0, 1]]


True

(OPTIONAL) Apply identity transformation to the selected surface to visualize the change.

In [35]:
# move to original position
client.apply_transformation_to_selected_surface(np.eye(4), verbose=True)

✅ Transformation applied to surface selected
📦 Response: Received payload [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]


True

# (2) Fine Registration

## (2.1) Creating Surface Cutouts
For fine registration we need to cut out a piece of the target surface to limit the region our source is matched two. 

For this, we need to draw an annotation on the REF surface containing the MOV surface. Then we need to select this cutout annotation and the TGT surface we want to cut out from.

👈 draw cutout annotation 

👈 select cutout annotation (automatically after finishing the drawing)

👈 select REF surface

In [37]:
json_data = client.query_annotation_as_json()
points = np.array(json.loads(json_data))

# Create o3d point cloud object from cutout points
ref_pcd = o3du.create_point_cloud_from_array(points)

👈 select MOV surface

In [38]:
json_data = client.query_annotation_as_json()
points = np.array(json.loads(json_data))

# Create o3d point cloud object from cutout points
mov_pcd = o3du.create_point_cloud_from_array(points)

## (2.2) Employing Iterative Closest Point Optimization

In [42]:
icp_result = o3du.refine_registration_icp(
    mov_pcd, 
    ref_pcd, 
    alignment_trafo, 
    voxel_size=0.05, 
    max_correspondence_distance=0.075
)

Running ICP fine registration...
Voxel size: 0.05, Max correspondence distance: 0.075, Iterations: 200
Pre-alignment (Helmert):
[[ 9.99278651e-01 -5.12201329e-04  3.79725700e-02 -3.86306918e+04]
 [ 8.57235258e-04  9.99958493e-01 -9.07067451e-03  9.26347161e+03]
 [-3.79663479e-02  9.09668281e-03  9.99237613e-01 -1.18965122e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

ICP Refinement Result:
[[ 9.99599322e-01  2.45967787e-03  2.81983344e-02 -3.77063639e+04]
 [-2.45769055e-03  9.99996974e-01 -1.05134706e-04  1.84303067e+03]
 [-2.81985077e-02  3.57898006e-05  9.99602342e-01  2.00546607e+04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


👈 select MOV surface

In [47]:
# Apply final result
client.apply_transformation_to_selected_surface(icp_result.transformation, verbose=True)

✅ Transformation applied to surface selected
📦 Response: Received payload [[0.9995993216881628, 0.002459677870854857, 0.028198334442729303, -37706.363912601846], [-0.0024576905484270627, 0.9999969743473568, -0.00010513470588332556, 1843.0306723274937], [-0.028198507721871224, 3.578980064415897E-05, 0.9996023423748834, 20054.660704870585], [0, 0, 0, 1]]


True

(OPTIONAL) Apply coarse transformation to the MOV surface to visualize the change.

In [46]:
# Apply transformation to selected surface
client.apply_transformation_to_selected_surface(alignment_trafo, verbose=True)

✅ Transformation applied to surface selected
📦 Response: Received payload [[0.9992786506159889, -0.0005122013288448336, 0.03797257000635512, -38630.69177934702], [0.0008572352579089507, 0.9999584931444213, -0.009070674509198184, 9263.471606392879], [-0.03796634787283878, 0.009096682809571488, 0.9992376127783926, -1189.6512213787064], [0, 0, 0, 1]]


True

# (4) Validation

In [75]:
T = icp_result.transformation  # 4x4 matrix

mov_pcd.transform(T)

offset = mov_pcd.get_center()  # or any reference origin

mov_pcd.translate(-offset)
ref_pcd.translate(-offset)

o3d.io.write_point_cloud("mov.ply", mov_pcd)
o3d.io.write_point_cloud("ref.ply", ref_pcd)

True

In [63]:
o3du.run_m3c2(
    "C:\\Program Files\\CloudCompare\\CloudCompare.exe",
    "ref.ply",
    "mov.ply",
    "param_file.txt")